### ISSUE TITLE
pip3 install -r requirements.txt have invalid syntax

### ISSUE THREAD

**Issue by axtive1209** [nschapeler/GDBot#3]
i tried to use gdbot and downloaded python 3.6
and i typed pip3 install -r requirements.txt and invalid syntax
am i have to use older version of python?

**Comment by nschapeler** [comment]
Hi axtive,

I just tried it out and it is working by me - Make sure you're in the correct directory (GDBot). Once you've done that, try again. As I don't know your development environment, maybe the correct command would be ```  pip install -r requirements.txt ``` by you. If that still doesn't work, please copy the full error message.

**Comment by nschapeler** [comment]
Haven't heard from you in a while, let me know if you still need help

**Comment by Aubergine111** [comment]
i'm fine thanks

2021년 6월 24일 (목) 오전 1:27, Nicolas Schapeler ***@***.***>님이 작성:
